# Jenkins CI/CD Configuration for XHS Poster
# This file provides additional configuration for the Jenkins pipeline

# Build Configuration
build:
  go_version: "1.24"
  timeout: "30m"
  
  # Build targets
  targets:
    - os: linux
      arch: amd64
    - os: windows
      arch: amd64
    - os: darwin
      arch: amd64

# Testing Configuration
testing:
  coverage_threshold: 70
  timeout: "10m"
  
  # Test commands
  commands:
    unit: "go test -v -race -coverprofile=coverage.out ./..."
    integration: "./quick_test_post.sh"
    security: "gosec ./..."

# Quality Gates
quality:
  lint:
    enabled: true
    timeout: "5m"
    fail_on_error: false
    
  format:
    enabled: true
    fail_on_error: true
    
  vet:
    enabled: true
    fail_on_error: true
    
  security:
    enabled: true
    fail_on_error: false

# Deployment Configuration
deployment:
  # Environments
  environments:
    staging:
      branches: ["develop", "feature/*"]
      auto_deploy: false
      
    production:
      branches: ["main", "master"]
      auto_deploy: false
      require_approval: true

# Notifications
notifications:
  slack:
    enabled: false
    webhook: ""
    channels:
      success: "#ci-success"
      failure: "#ci-alerts"
      
  email:
    enabled: false
    recipients: []
    
  github:
    enabled: true
    status_checks: true

# Artifacts
artifacts:
  retention_days: 30
  
  # Files to archive
  files:
    - "xhs-poster-*"
    - "release/*"
    - "coverage.html"
    - "coverage.out"
    - "gosec-report.json"

# Cache Configuration
cache:
  go_modules:
    enabled: true
    key: "go-mod-{{ checksum \"go.sum\" }}"
    
  build_cache:
    enabled: true
    key: "build-{{ .Branch }}-{{ .Revision }}"
